insert or replace into LocalizedText
    (Language,      Tag,                                                                Text)
values
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_TITLE",                                 "部落联合"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_DESCRIPTION",                           ""),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_EFFECT",                                "作为多个部落的共同盟主，你在击败了当地部落后，让剩余的部众对你俯首称臣。你将如何决定这些蛮夷的命运？是接受他们作为边地戍卫，还是将他们抓作劳力，又或是将他们迁徙到附近的城市以作开化？"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_A",                              "戍守边疆"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_B",                              "填充劳力"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_C",                              "徙居城市"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_UNITS",                             "周围的{1_Amount}个野蛮人战斗单位会转化为你的单位"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_BUILDER",                           "周围的{1_Amount}个野蛮人战斗单位消失，你获得{2_Amount}个建造者"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_POP",                               "周围的{1_Amount}个野蛮人战斗单位消失，{2_CITYNAME}获得{1_Amount} [ICON_Citizen] 人口。"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_STATE_LABOR",                        "[COLOR_RED]需要先完成市政“国家劳动力”才能进行选择[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_EARLY_EMPIRE",                       "[COLOR_RED]需要先完成市政“帝国初期”才能进行选择[ENDCOLOR]"),   

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_TITLE",                        "军事改革"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_DESCRIPTION",                  ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_EFFECT",                       "在征服了两个周边部落后，我们挑选出了各部族的精锐勇士作为常备部队。我们的军事组织空前强大，而他们将作为我们开拓的利刃！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_CONTINUE",                     "为了部落！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_UNLOCK",                       "为部落联盟政体增加一个军事政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_TITLE",                        "经济改革"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_DESCRIPTION",                  ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_EFFECT",                       "在融合了五个周边村庄后，我们初步建立了部落中不同部族间的商贸体系，紧密的商业联系将成为部落团结的关键。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_CONTINUE",                     "为了部落！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_UNLOCK",                       "为部落联盟政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_TITLE",                          "军事改革"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_EFFECT",                         "来自{1_CITYNAME}的军事传统让我们对军队建设有了更深的理解，现在我们可以更从容地面对战争了。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_CONTINUE",                       "军事霸权的第一步"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_UNLOCK",                         "为城邦共主政体增加一个军事政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_TITLE",                          "经济改革"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_EFFECT",                         "来自{1_CITYNAME}的商业传统让我们对贸易有了更深的理解。现如今，我们的贸易网络空前强盛。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_CONTINUE",                       "经济霸权的第一步"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_UNLOCK",                         "为城邦共主政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_TITLE",                          "洪水之后"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_EFFECT",                         "洪水淹没了{1_cityname}的周边地区，多亏了大浴场配套的水利设施，我们第{2_times}次几乎没有损失的度过了灾难。祭司将{1_cityname}的市民们召集在大浴场，在进行祭祀后宣布了洪水的善后措施。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_A",                       "庆祝劫后余生"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_B",                       "收容洪水难民"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_C",                        "扩建城市规模"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_AMENITY",                    "为{1_cityname}+1 [ICON_Amenities] 宜居度"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_POP",                        "为{1_cityname}+1 [ICON_Citizen] 人口"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_HOUSING",                    "为{1_cityname}+2 [ICON_Housing] 住房"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_NO_HOME",                        "[COLOR_RED]{1_cityname} 没有足够的住房，不能收容更多难民[ENDCOLOR]"),


    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_TITLE",                                      "壁画艺术"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_DESCRIPTION",                                ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_EFFECT",                                     "这个村庄的村民会制作很多颜料绘制壁画，连{1_CITYNAME}的艺术家看到了都会感叹壁画之鲜艳多彩。也许我们可以带走最好的壁画，又或者，让我们的艺术家来研究一下？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CHOICE_A",                                   "搬走最好的壁画"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CHOICE_B",                                   "学习壁画的颜料"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CULTURE",                                    "宫殿+1 [ICON_Culture] 文化值[NEWLINE]完成帝国初期后改为+2 [ICON_Culture] 文化值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_SCIENCE",                                    "宫殿+1 [ICON_Science] 科技值[NEWLINE]完成砌砖后改为+2 [ICON_Science] 科技值"),


    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_TITLE",                            "人祭"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_DESCRIPTION",                      ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_EFFECT",                           "这里的聚落似乎正在用动物和活人进行祭祀以取悦鬼神，他们一开始尝试抓住你的使者，但很快就被击退。在成功进行交流后，他们邀请你也来参加祭祀。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_A",                         "用动物祭祀"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_B",                         "用活人祭祀"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_GAIN_FAITH",                       "获得{1_AMOUNT} [ICON_FAITH] 信仰值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_LOSE_POP",                         "{1_CITYNAME}失去 1 [ICON_CITIZEN] 人口"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_NO_POP_TO_LOSE",                   "[COLOR_RED]{1_CITYNAME}人口不足2，无法失去 [ICON_CITIZEN] 人口[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_TITLE",                               "制图专家"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                         ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_EFFECT",                              "这里的村民很快就猜到了我们的{1_UNITNAME}来自哪里，原来当地有一户人家擅长制作地图，为村落外出交流提供了很大的便利。也许我们应该拿走他们的地图，或者请他们加入我们的队伍？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_A",                            "抢走地图"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_B",                            "抓走制图师"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_SHOW_MAP",                            "获得6格内的地图"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_HORIZON",                             "你的{1_UNITNAME}获得1额外视野"),
    ("zh_Hans_CN",  "LOC_ABILTY_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                  "+1额外视野，来自绑架的制图师。"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_TITLE",                                 "神奇的草药"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_DESCRIPTION",                           ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_EFFECT",                                "村民向你献上几种草药，据说在祭祀中服用这些草药就可以与神灵交流。他们提醒你，这些草药只有在生吃时才会有最大的效力。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_A",                              "那就生吃吧"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_B",                              "熟食才安全"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_KILL_UNIT",                             "你的{1_UNITNAME}遇害了"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_FAITH",                                 "获得{1_AMOUNT} [ICON_FAITH] 信仰值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_HEAL_UNIT",                             "你的{1_UNITNAME}恢复了全部生命值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_MOVEMENT",                              "你的{1_UNITNAME}立刻获得5点 [ICON_MOVEMENT] 移动力"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_TITLE",                                     "饥荒"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_DESCRIPTION",                               ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_EFFECT",                                    "也许我们来晚了，但也许还没有那么晚。这一带的饥荒已经持续了一段时间了，我们的{1_UNITNAME}来到这里就是这里最大的救星。我们可以带走那些还有余力跟着我们{1_UNITNAME}的民众，但带走更多的人，就需要{2_CITYNAME}的帮助了。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_CHOICE_A",                                  "带走还能行动的人"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_CHOICE_B",                                  "从{1_CITYNAME}派出救援队伍"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_GAIN_1_POPULATION",                         "{1_CITYNAME}获得1 [ICON_Citizen] 公民"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_GAIN_2_POPULATION",                         "{1_CITYNAME}获得2 [ICON_Citizen] 公民"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_PAY_GOLD",                                  "失去100 [ICON_Gold] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_NO_GOLD_TO_LOSE",                           "[COLOR_RED] [ICON_Gold] 金币不足100，无法进行援助。[ENDCOLOR]"),


    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_TITLE",                      "古老工事"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_DESCRIPTION",                ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_EFFECT",                     "我们的{1_UNITNAME}到达村庄时，村子里的人早已躲进了一座看起来颇有年头的防御工事里。工事看起来颇为完备，易守难攻，但破败的墙体也说明这里并非没有破绽可寻。是组织强攻，还是搜刮村里留下的物资就走？。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_A",                   "组织进攻"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_B",                   "搜刮物资"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_GOOD_END",                   "30%概率触发事件“攻克工事”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_BAD_END",                    "70%概率你的{1_UNITNAME}失去25生命值，触发事件“没有进展”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_STOP",                       "获得25 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_NO_STRENNGTH",               "[COLOR_RED]只有战斗单位才能进行此项[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_TITLE",                    "攻克工事"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_DESCRIPTION",              ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_EFFECT",                   "长久的进攻后，工事终于被拿下，我们的{1_UNITNAME}胜利凯旋"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_CONTINUE",                 "伟大胜利！"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_GOLD",                     "获得100 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_PROMOTION",                "你的{1_UNITNAME}获得一次升级"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_TITLE",                    "没有进展"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_DESCRIPTION",              ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_EFFECT",                   "数次针对工事薄弱点的进攻均无功而返，我们的{1_UNITNAME}也损失惨重。还要继续吗？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_A",                 "继续！"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_B",                 "见好就收"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_GOOD_END",                 "30%概率触发事件“攻克工事”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_BAD_END",                  "70%概率你的{1_UNITNAME}失去25生命值，触发事件“没有进展”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_STOP",                     "获得25 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_UNIT_KILLED",              "[COLOR_RED]在上一轮进攻中，你的{1_UNITNAME}已溃败[ENDCOLOR]");


insert or replace into LocalizedText
    (Language,      Tag,                                                                Text)
values
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_TITLE",                                 "Tribal Confederation"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_DESCRIPTION",                           ""),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_EFFECT",                                "As the leader of tribal confederate, you have defeated the local tribes and forced the others to bend their knees. How will you decide the fate of these barbarians? Will you accept them as border guards, capture them as forced labor, or relocate them to nearby cities and make them civilized?"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_A",                              "Border Guard"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_B",                              "Forced Labor"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_C",                              "Relocation"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_UNITS",                             "{1_Amount} nearby Barbarian combat units are converted to yours."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_BUILDER",                           "{1_Amount} nearby Barbarian combat units disappear, and you receive {2_Amount} Builders."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_POP",                               "{1_Amount} nearby Barbarian combat units disappear, {2_CITYNAME} receives {1_Amount} [ICON_Citizen] Population."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_STATE_LABOR",                        "[COLOR_RED]Can only be chosen after researching the State Workforce civic.[ENDCOLOR]"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_EARLY_EMPIRE",                       "[COLOR_RED]Can only be chosen after researching the Early Empire civic.[ENDCOLOR]"),   

    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_TITLE",                        "Military Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_DESCRIPTION",                  ""),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_EFFECT",                       "After conquering two nearby tribes, we have chosen veteran warriors from every tribe to form a standing army. Our military organization is stronger than ever, and they will serve as the blade to cut open the way of expansion!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_CONTINUE",                     "For the horde!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_UNLOCK",                       "Adds a military policy slot for the Tribal Confederate government."),

    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_TITLE",                        "Economic Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_DESCRIPTION",                  ""),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_EFFECT",                       "After assimilating five nearby villages, we have established the commerce system among different clans in our horde, a tight trade relationship among clans will be key to our unity."),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_CONTINUE",                     "For the horde!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_UNLOCK",                       "Adds an economic policy slot for the Tribal Confederate government."),

    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_TITLE",                          "Military Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_DESCRIPTION",                    ""),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_EFFECT",                         "The military traditions of {1_CITYNAME} have brought us better understanding with establishing an army, now we can face war with ease."),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_CONTINUE",                       "The first step to military hegemony"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_UNLOCK",                         "Adds a military policy slot for the City-State Suzerainty government."),

    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_TITLE",                          "Economic Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_DESCRIPTION",                    ""),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_EFFECT",                         "The economic traditions of {1_CITYNAME} have brought us better understanding with commere. Now, the prosperity of our trade network is unprecendented."),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_CONTINUE",                       "The first step to economic hegemony"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_UNLOCK",                         "Adds an economic policy slot for the City-State Suzerainty government."),

    ("en_US",  "LOC_EVENT_GOODY_MURAL_TITLE",                                      "Cave Painting Arts"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_DESCRIPTION",                                ""),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_EFFECT",                                     "The residents of this village know how to mix dyes to draw cave paintings, even the artists of {1_CITYNAME} praised the vividness of their colors. Maybe we can take the finest cave paintings, or maybe, leave them to the study of our artists?"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CHOICE_A",                                   "Take the finest cave paintings"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CHOICE_B",                                   "Study about the dyes"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CULTURE",                                    "+1 [ICON_Culture] Culture to the Palace[NEWLINE]Increased to +2 [ICON_Culture] Culture after researching the Early Empire civic."),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_SCIENCE",                                    "+1 [ICON_Science] Science to the Palace[NEWLINE]Increased to +2 [ICON_Science] Science after researching the Masonry technology."),


    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_TITLE",                            "Human Sacrifice"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_DESCRIPTION",                      ""),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_EFFECT",                           "This settlement seems to be sacrificing animals and living humans to please the ghosts and deities. They tried to capture your messengers in the first place, but we fought them back. After a successful discussion, they have invited you to join the ritual."),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_A",                         "Sacrifice with animals"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_B",                         "Sacrifice with humans"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_GAIN_FAITH",                       "Receive {1_AMOUNT} [ICON_FAITH] Faith"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_LOSE_POP",                         "{1_CITYNAME} loses 1 [ICON_CITIZEN] Population"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_NO_POP_TO_LOSE",                   "[COLOR_RED]{1_CITYNAME} has less than 2 [ICON_CITIZEN] Population, cannot lose [ICON_CITIZEN] Population any more[ENDCOLOR]"),

    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_TITLE",                               "Cartographer"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                         ""),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_EFFECT",                              "The villagers here figures out when our {1_UNITNAME} came from in the blink of an eye. It turns out that there is a local family who is good at making maps, which provides a great convenience for the village to reach out beyond their border. Maybe we should take their maps, or let them join our team?"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_A",                            "Take the map"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_B",                            "Kidnap the cartographer"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_SHOW_MAP",                            "Reveals map within 6 tiles"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_HORIZON",                             "Your {1_UNITNAME} receives +1 additional sight"),
    ("en_US",  "LOC_ABILTY_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                  "+1 additional sight, from the kidnapped cartographer"),

    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_TITLE",                                 "Mysterious Herbs"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_DESCRIPTION",                           ""),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_EFFECT",                                "The villagers present you with several herbs, legends said they allow communication with the spirits when taken during rituals. They remind you that these herbs are only potent when eaten raw."),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_A",                              "Eat it raw"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_B",                              "Cooked food is safer"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_KILL_UNIT",                             "Your {1_UNITNAME} dies"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_FAITH",                                 "Receive {1_AMOUNT} [ICON_FAITH] Faith"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_HEAL_UNIT",                             "Your {1_UNITNAME} fully heals"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_MOVEMENT",                              "Your {1_UNITNAME} receives 5 [ICON_MOVEMENT] Movement immediately"),

    ("en_US",  "LOC_EVENT_GOODY_FAMINE_TITLE",                                     "Famine"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_DESCRIPTION",                               ""),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_EFFECT",                                    "We may come late, but not too late. Maybe we're late to the party, but maybe not that late. The famine in this area has been going on for some time now, and our {1_UNITNAME} coming here is the greatest savior here. We can bring the people who still have remaining stamina to follow our {1_UNITNAME}, but taking more people will require the help of {2_CITYNAME}."),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_CHOICE_A",                                  "Take those who can still walk"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_CHOICE_B",                                  "Send a rescue team from {1_CITYNAME}"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_GAIN_1_POPULATION",                         "{1_CITYNAME} receives 1 [ICON_Citizen] Population"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_GAIN_2_POPULATION",                         "{1_CITYNAME} receives 2 [ICON_Citizen] Population"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_PAY_GOLD",                                  "Lose 100 [ICON_Gold] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_NO_GOLD_TO_LOSE",                           "[COLOR_RED] Less than 100 [ICON_Gold] Gold, cannot send a rescue team[ENDCOLOR]"),


    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_TITLE",                      "Seasoned Fortification"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_DESCRIPTION",                ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_EFFECT",                     "When our {1_UNITNAME} reached the village, the villagers had taken refuge in a fortification that looked quite old. The fortification looked well established and highly defensible, but the crumbling walls showed it is not flawless. Should we launch a siege, or just scavenge the supplies left behind in the village and leave?"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_A",                   "Launch a Siege"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_B",                   "Scavenge the Supplies"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_GOOD_END",                   "30% to trigger the event“Successful Siege”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_BAD_END",                    "70% to trigger the event “Stalemate”, and your {1_UNITNAME} loses 25 HP"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_STOP",                       "Receives 25 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_NO_STRENNGTH",               "[COLOR_RED]Only combat unit can choose this option[ENDCOLOR]"),

    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_TITLE",                    "Successful Siege"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_DESCRIPTION",              ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_EFFECT",                   "After a prolonged siege, the fortification is captured, and our {1_UNITNAME} triumphs in victory"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_CONTINUE",                 "A great victory!"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_GOLD",                     "Receives 100 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_PROMOTION",                "Your {1_UNITNAME} receives a promotion"),

    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_TITLE",                    "Stalemate"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_DESCRIPTION",              ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_EFFECT",                   "Several attacks against weak points of the fortifications were unsuccessful, and our {1_UNITNAME} suffered heavy casualties. Should we continue?"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_A",                 "Push on!"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_B",                 "Retreat"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_GOOD_END",                 "30% to trigger the event“Successful Siege”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_BAD_END",                  "70% to trigger the event “Stalemate”, and your {1_UNITNAME} loses 25 HP”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_STOP",                     "Receives 25 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_UNIT_KILLED",              "[COLOR_RED]Your {1_UNITNAME} is routed during the last siege[ENDCOLOR]");




